
* Data: Mit Markus gesprochen (3.Sept.2010):

 - Die data/test_*.rda Daten welche nur in tests/
   gebraucht werden, sollen nicht "exponiert" werden.

 - Die andern sind momentan "falsch" dokumentiert, sowohl formal (-> R CMD check),
   als auch inhaltlich {die *Namen* strings sind "dokumentiert"; sonst kein Inhalt}.

 - Auch hat es z.T. mehrere Objekte pro *.rda  die inhaltlich zusammengehören;
   MM denkt, die sollten wohl zusammen in eine Liste (mit kurzem Namen!).

 Wo gebraucht:

  pcalg$ grep-r binaryData
  ./man/pc.Rd:data(binaryData)
  ./man/skeleton.Rd:data(binaryData)
  pcalg$ grep-r discreteData
  ./inst/doc/pcalgDoc.Snw:data set \code{discreteData} (which consists of $p=5$ discrete
  ./inst/doc/pcalgDoc.Snw:data(discreteData)
  ./man/pc.Rd:data(discreteData)
  ./man/skeleton.Rd:data(discreteData)
  pcalg$ grep-r gaussianData
  ./inst/doc/pcalgDoc.Snw: data(gaussianData)
  ./inst/doc/pcalgDoc.Snw:\code{gaussianData} (which consists of $p=8$ variables and $n=5000$
  ./inst/doc/pcalgDoc.Snw:data(gaussianData)
  ./inst/doc/pcalgDoc.Snw:data(gaussianData)
  ./inst/doc/pcalgDoc.Snw:data(gaussianData)
  ./inst/doc/pcalgDoc.Snw:data(gaussianData) ## contains data matrix datG
  pcalg$ grep-r idaData
  ./inst/doc/pcalgDoc.Snw:data(idaData)
  pcalg$ grep-r latentVarGraph
  ./inst/doc/pcalgDoc.Snw:data(latentVarGraph)

## Here, you get their contents:

 for(f in list.files("~/R/Pkgs/pcalg/data/", full.names=TRUE)) {
    bf <- basename(f)
    nam <- sub("\\.rda$", '', bf)
    cat("\n", bf, ":\n-----------------\n", sep="")
    attach(f)
    print(ls.str(pos=2))
    detach()
 }


* DESCRIPTION:
** Depends:  too many; I do not believe they are all "dependently" needed.

*** DONE Remove more 'Depends:': vcd, RBGL.
    - vcd: I've eliminated it, and all the 'R CMD check' still run
    - RBGL: .. ok, only a few needed
    - graph: import quite a few; now found all examples -- is this (not
      attaching 'graph') acceptable to the current pcalg users ?
**** Note: 'abind' and 'corpcor' are kept *ONLY* because they have no namespace!
    - abind: abind() needed in gSquareBin() & *Dis() -- once only, each
    - corpcor: pseudoinverse() [ -> fast.svd() .. non-optimal "A %% diag(.)" ]



* Remarks on specific functions and issues:

** gSquareBin(), gSquareDis():
  - returns a P-value but not the test statistic.  Should *really* return
    an object of (standard S3 class) "htest" (which contains P-value, test
    statistic, ...)!

** fci() :
  - returns the adjacency matrix "@ amat" (among other things),
    a simple matrix with entries in {0,1,2,3}.
    It would be nice to allow *sparse* matrices here,
    e.g., by using the  "Matrix" class from the Matrix package.

    This makes sense mostly if it's realistic to have quite sparse
    and relatively large sets of variables.

** gAlgo-class: consider using setMethod(., "gAlgo")
   instead of all methods (plot, summary) for both pcAlgo and fciAlgo

** DONE myCItest() in  der Vignette inst/doc/pcalgDoc.Snw
   instead of lm() twice, use lm.fit *once* (*multivariate* regression).
   This will probably be much faster.

** ida():  argument  'all.dags' is never used, i.e., never tested.

** dsepTest(): gibt 0 / 1  zurück; wieso nicht einfach FALSE/TRUE wie dsep()?

* NAMESPACE:

*** DONE Look at ./NAMESPACE  and replace *ALL*  the  Imports() by
     ImportsFrom(.)



*** TODO What do we export / what not?
    Currently, there is  ./man/pcalg-internal.Rd   with man \alias{}es
    and only few functions in "Usage".
    The concept of such "internal" functions really *predates* the use
    of NAMESPACEs and is now obsolete.

    I think almost all of these should be *removed* for the *.Rd page,
    *and* from NAMESPACE.
    Very few maybe could be kept, but then we should plan to document them
    (on a different *.Rd file)
**** Goal: Get rid of ./man/pcalg-internal.Rd   entirely.
